application: miwc-web
version: 2
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: django
  version: "1.5"
- name: MySQLdb
  version: "latest"
  
builtins:
- django_wsgi: on

env_variables:
  DJANGO_SETTINGS_MODULE: 'miwc.settings'

handlers:
- url: /static
  static_dir: static
  secure: always
- url: /.*
  script: miwc.wsgi.application
  secure: always